spring:
  profile:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/notepad
    username: noteadm
    password: noteadm
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
  messages:
    cache-seconds: 0

flyway.enabled: true
endpoints.sensitive: false

---


test_postgresql_host: ${ENV_TEST_POSTGRESQL_HOST:localhost}

spring:
#  profiles: test
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://${test_postgresql_host}:5432/notepad
    username: noteadm
    password: noteadm
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway.enabled: true
endpoints.sensitive: false

---

# BEGIN FIX 
testing_datasource_url: jdbc:postgresql://localhost:5432/notepad
testing_datasource_username: noteadm 
testing_datasource_password: noteadm
# END FIX

spring:
#  profiles: testing
  config:
    activate:
      on-profile: testing
  datasource:
    url: ${testing_datasource_url}
    username: ${testing_datasource_username}
    password: ${testing_datasource_password}
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway.enabled: true
endpoints.sensitive: false
logging.config: /etc/notepad/logback-spring.xml

---


# BEGIN FIX 
staging_datasource_url: jdbc:postgresql://localhost:5432/notepad
staging_datasource_username: noteadm 
staging_datasource_password: noteadm
# END FIX

spring:
#  profiles: staging
  config:
    activate:
      on-profile: staging
  datasource:
    url: ${staging_datasource_url}
    username: ${staging_datasource_username}
    password: ${staging_datasource_password}
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway.enabled: true
endpoints.sensitive: false
logging.config: /etc/notepad/logback-spring.xml

---


# BEGIN FIX 
production_datasource_url: jdbc:postgresql://localhost:5432/notepad
production_datasource_username: noteadm 
production_datasource_password: noteadm
# END FIX

spring:
#  profiles: production
  config:
    activate:
      on-profile: production
  datasource:
    url: ${production_datasource_url}
    username: ${production_datasource_username}
    password: ${production_datasource_password}
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway.enabled: true
endpoints.sensitive: false
logging.config: /etc/notepad/logback-spring.xml
